version: "3.5"
services:
  ckan:
    build:
      context: .
      dockerfile: ./stack/ckan/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./ckanext-basedosdados:/app/ckanext-basedosdados
      - ./vendor/ckan:/ckan
      - ./configs/:/app/configs/
      - ./stack/ckan/assets:/app/uploads/
      - ckan_home:/root
    environment:
      - BETTER_EXCEPTIONS=1
      - WERKZEUG_DEBUG_PIN=off
    command: "ckan run --host 0.0.0.0 --port 5000"
  db:
    build:
      context: .
      dockerfile: ./stack/postgresql/Dockerfile
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  solr:
    ports: ["8983:8983"]
    build:
      context: .
      dockerfile: stack/solr/Dockerfile

  next:
    build:
      context: next
    volumes:
      - ./next:/app
    command: ["yarn", "run", "dev"]

  strapi:
    command: ["yarn", "run", "develop"]
    environment:
      - NODE_ENV=development

  nginx:
    volumes:
      - ./configs/nginx.dev.conf:/etc/nginx/nginx.conf:ro

volumes:
  pg_data:
  ckan_home:
